name: CI workflow
on: 
  push:
    branches: push on main branch
  pull_request: pull_request on main branch

jobs:
  build: 
    runs_on: ubuntu-latest
    container: python:3.9-slim
    steps: 
      - name: Checkout
        uses: actions/Checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      